logging:
  level:
    be.albatroz: INFO
    org:
      springframework: INFO
      hibernate.stat: INFO
      hibernate.hql: INFO

spring:

  http:
    log-request-details: true

  datasource:
    hikari:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      jdbc-url: "jdbc:hsqldb:mem:javacase;DB_CLOSE_DELAY=-1:"
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    baseline-description: Initial DB
    baseline-version: -1 # version to start migration
    baseline-on-migrate: true   #
    check-location: false # Check that migration scripts location exists.
    enabled: true # Enable flyway.
    locations: be.albatroz.javacase.infrastructure.migrations # classpath:db/migration # locations of migrations scripts
    table: schema_version

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#      write-dates-as-timestamps: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
#      write-date-timestamps-as-nanoseconds: false
